quarkus:
  kubernetes-client:
    trust-certs: true
  kubernetes-config:
    enabled: true
    config-maps:
      - customers-config
  hibernate-orm:
    database:
      generation: drop-and-create
    sql-load-script: load.sql
  datasource:
    db-kind: h2
    username: sa
    password: sa
    jdbc:
      url: jdbc:h2:mem:customers;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  log:
    level: INFO
    category:
      "org.meetup.openshift.rhoar":
        level: DEBUG
  jaeger:
    endpoint: http://jaeger-collector.rhoar.svc:14268/api/traces
    sampler-type: const
    sampler-param: 1
