swarm:
  datasources:
    data-sources:
      productsDS:
        driver-name: postgresql
        connection-url: jdbc:postgresql://postgresql-inventory.rhoar.svc:5432/inventory
        user-name: inventory
        password: inventory
  logging:
    loggers:
      org.meetup.openshift.rhoar.inventory:
        level: DEBUG
jaeger:
  endpoint: http://jaeger-collector.rhoar.svc:14268/api/traces