apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orders
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rromannissen/rhoar-microservices-demo.git
    targetRevision: quarkus17
    path: orders/config
  destination:
    server: https://kubernetes.default.svc
    namespace: order-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
