spring:
  datasource:
    url: jdbc:postgresql://postgresql-orders:5432/orders
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create


endpoints:
  enabled: true

opentracing:
  jaeger:
    udp-sender:
      host: jaeger-all-in-one-inmemory-collector
      port: 14268
