spring:
  datasource:
    url: jdbc:postgresql://postgresql-orders:5432/orders
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      temp:
        use_jdbc_metadata_defaults: false


endpoints:
  enabled: true

opentracing:
  jaeger:
    http-sender:
      url: http://jaeger-all-in-one-inmemory-collector:14268/api/traces
